package com.example.harmonialauncher.lock;

import android.app.Dialog;
import android.content.Context;
import android.util.Log;
import android.view.View;
import android.view.Window;
import android.widget.Button;
import android.widget.NumberPicker;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.example.harmonialauncher.Helpers.TimeHelper;
import com.example.harmonialauncher.R;

public class LockTimeDialog extends Dialog {
    private static final String TAG = LockTimeDialog.class.getSimpleName();

    private LockMedia media;
    public LockTimeDialog(@NonNull Context context, LockMedia media) {
        super(context);
        this.media = media;
        initialize();
    }

    public LockTimeDialog(@NonNull Context context, int themeResId, LockMedia media) {
        super(context, themeResId);
        this.media = media;
        initialize();
    }

    protected LockTimeDialog(@NonNull Context context, boolean cancelable, @Nullable OnCancelListener cancelListener) {
        super(context, cancelable, cancelListener);
        initialize();
    }

    private void initialize()
    {
        //Disable default title generated by android
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        //Allow user to cancel dialog by clicking anywhere outside dialog box
        setCancelable(true);
        setContentView(R.layout.time_picker);

        final NumberPicker hours = findViewById(R.id.numberPicker1);
        final NumberPicker minutes = findViewById(R.id.numberPicker2);
        Button ok = findViewById(R.id.submit_time_button);
        Button cancel = findViewById(R.id.cancel_button);

        hours.setMinValue(0);
        hours.setMaxValue(99);
        hours.setWrapSelectorWheel(false);
        minutes.setMinValue(0);
        minutes.setMaxValue(59);
        minutes.setWrapSelectorWheel(false);

        ok.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                int hour = hours.getValue();
                int minute = minutes.getValue();
                TimeHelper time = new TimeHelper(hour, minute, TimeHelper.INPUT_RELATIVE);

                if (media.getType() == LockMedia.APP)
                {
                    LockManager.lock(media.getPackageName(), time);
                    LockStatusChangeListener.onStatusChanged();
                    Log.d(TAG, "LOCKED APP: " + media.getName() + " for time: " + time.getTimeRemaining());
                }
                else if (media.getType() == LockMedia.WEBSITE)
                {
                    Log.d(TAG, "LOCKED THE FOLLOWING WEBSITE: " + media.getURL());
                }

                dismiss();
            }
        });

        cancel.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                cancel();
            }
        });
    }

}
