package com.example.harmonialauncher.lock;

import android.app.AlertDialog;
import android.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.Window;
import android.widget.NumberPicker;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.DialogFragment;
import androidx.lifecycle.ViewModelProvider;

import com.example.harmonialauncher.Helpers.TimeHelper;
import com.example.harmonialauncher.R;

public class LockTimeDialog extends DialogFragment {
    private static final String TAG = LockTimeDialog.class.getSimpleName();

    private LockMedia media;
    private LockActivityViewModel vm;

    public LockTimeDialog(int resource, LockMedia media) {
        super(resource);
        this.media = media;
    }

    public void onAttach(Context context)
    {
        super.onAttach(context);

        vm = new ViewModelProvider(requireActivity()).get(LockActivityViewModel.class);
    }

    @NonNull
    public Dialog onCreateDialog(@Nullable Bundle savedInstanceState) {
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        LayoutInflater inflater = requireActivity().getLayoutInflater();
        View customView = inflater.inflate(R.layout.time_picker, null);

        NumberPicker hours = customView.findViewById(R.id.numberPicker1);
        NumberPicker minutes = customView.findViewById(R.id.numberPicker2);
        hours.setMinValue(0);
        hours.setMaxValue(99);
        hours.setWrapSelectorWheel(false);
        minutes.setMinValue(0);
        minutes.setMaxValue(59);
        minutes.setWrapSelectorWheel(false);

        builder.setView(customView)
                .setTitle(R.string.set_lock_time)
                .setPositiveButton(R.string.ok, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        int hour = hours.getValue();
                        int minute = minutes.getValue();
                        TimeHelper time = new TimeHelper(hour, minute, TimeHelper.INPUT_RELATIVE);

                        if (media.getType() == LockMedia.APP) {
                            vm.lockApp(media.getPackageName(), time.getAbsoluteTime());
                            LockStatusChangeListener.onLockStatusChanged();
                            Log.d(TAG, "LOCKED APP: " + media.getName() + " for time: " + time.getTimeRemaining());
                        } else if (media.getType() == LockMedia.WEBSITE) {
                            Log.d(TAG, "LOCKED THE FOLLOWING WEBSITE: " + media.getURL());
                        }

                        dialogInterface.dismiss();
                    }
                })
                .setNeutralButton(R.string.cancel, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        dialogInterface.dismiss();
                    }
                });

        AlertDialog d = builder.create();

        //Disable default title generated by android
        d.requestWindowFeature(Window.FEATURE_NO_TITLE);
        //Allow user to cancel dialog by clicking anywhere outside dialog box
        setCancelable(true);

        return d;
    }
}
