package com.example.harmonialauncher.LockActivity;

import android.app.ActionBar;
import android.app.Dialog;
import android.content.Context;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.os.CountDownTimer;
import android.util.Log;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.CompoundButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.NumberPicker;
import android.widget.PopupWindow;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.Spinner;
import android.widget.TextView;

import androidx.appcompat.widget.LinearLayoutCompat;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.LinearLayoutManager;

import com.example.harmonialauncher.AppObject;
import com.example.harmonialauncher.R;
import com.example.harmonialauncher.Util;
import com.example.harmonialauncher.lockManager.HarmoniaActivity;
import com.example.harmonialauncher.lockManager.LockManager;

import java.util.ArrayList;

public class LockActivity extends HarmoniaActivity {

    private static final String TAG = "Lock Activity";
    private Context context = this;

    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.lock_activity);

        //Populate LinearLayout with items
        //Each item consists of app icon, app name, and time picker.
        //At the bottom of the LinearLayout is a button which applies lock times to LockManager.
        LinearLayout ll = (LinearLayout) findViewById(R.id.lock_activity_linearlayout);
        ArrayList<AppObject> apps = Util.loadAllApps(this);
        for (AppObject a : apps)
        {
            LayoutInflater inflater = (LayoutInflater) getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            View v = inflater.inflate(R.layout.list_item, null);
            TextView text = (TextView) v.findViewById(R.id.app_name);
            ImageView icon = (ImageView) v.findViewById(R.id.app_icon);
            CheckBox check = (CheckBox) v.findViewById(R.id.lock_drop_down_list);

            text.setText(a.getName());
            if (a.getImage() != null)
                icon.setImageDrawable(a.getImage());
            else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP)
                icon.setImageDrawable(getResources().getDrawable(a.getImageId(), null));
            else
                icon.setImageDrawable(getResources().getDrawable(a.getImageId()));
            icon.setLayoutParams(new RelativeLayout.LayoutParams(Util.getRealScreenSize(this).x / 4, Util.getRealScreenSize(this).x / 4));
            check.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
                @Override
                public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                    if (!isChecked)
                        return;

                    final CheckBox check = (CheckBox)buttonView;

                    // Create NumberPicker popup
                    final Dialog d = new Dialog(context);

                    //Disable default title generated by android
                    d.requestWindowFeature(Window.FEATURE_NO_TITLE);
                    //Allow user to cancel dialog by clicking anywhere outside dialog box
                    d.setCancelable(true);
                    d.setContentView(R.layout.time_picker);
                    d.show();

                    final NumberPicker hours = (NumberPicker) d.findViewById(R.id.numberPicker1);
                    final NumberPicker minutes = (NumberPicker) d.findViewById(R.id.numberPicker2);
                    Button ok = (Button) d.findViewById(R.id.submit_time_button);
                    Button cancel = (Button) d.findViewById(R.id.cancel_button);

                    hours.setMinValue(0);
                    hours.setMaxValue(99);
                    hours.setWrapSelectorWheel(false);
                    minutes.setMinValue(0);
                    minutes.setMaxValue(59);
                    minutes.setWrapSelectorWheel(false);

                    //Find app object associated with checkbox press
                    LinearLayoutCompat parent = (LinearLayoutCompat) buttonView.getParent().getParent();
                    String appName = null;
                    for (int i = 0; i < parent.getChildCount(); i++) {
                        if (parent.getChildAt(i).getId() == R.id.app_name_layout) {
                            appName = ((TextView)((RelativeLayout) parent.getChildAt(i)).getChildAt(0)).getText().toString();
                            //This line shows a TextView within a RelativeLayout, which is wihtin the same LinearLayoutCompat at the
                            //RelativeLayout which holds our CheckBox. We extract the app name from that TextView.
                        }
                    }
                    if (appName == null)
                        return;
                    final AppObject app = Util.findAppByName(appName, context);

                    ok.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            int hour = hours.getValue();
                            int minute = minutes.getValue();
                            int millis = (hour * 3600000) + (minute * 60000);
                            LockManager.lock(app.getPackageName(), millis);
                            Log.d(TAG, "LOCKED APP: " + app + " for time: " + millis);
                            d.dismiss();
                        }
                    });

                    cancel.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            //TODO: Only unselect the button if the app lock timer has run out.
                            check.setChecked(false);
                            d.dismiss();
                            Log.d(TAG, "CANCEL DIALOG");
                        }
                    });
                }
            });

            ll.addView(v);
        }
    }

}
